print("welcome to the game")
print("step 1:Think of a number.")
print("step 2:Add 3 to that no.")
print("step 3:double that number.")
print("step 4:subtract 4.")
print("step 5:cut that in half.")
print("step 6:subtract your original number.")
print("press 'enter' two times to get the result.")
print()
print("your answer is 1!")
