input("Welcome to the game.Press enter to continue.")
input("step 1:Think of a number.")
input("step 2:Add 3 to that no.")
input("step 3:double that number.")
input("step 4:subtract 4.")
input("step 5:cut that in half.")
input("step 6:subtract your original number.")
input("press 'enter' two times to get the result.")
input()
input("your answer is 1!")
